/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.54).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.LoteGrid;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2024-04-01T14:41:59.684722023Z[GMT]")
@Validated
public interface ContribuintesLoteNotificacaoApi {

    @Operation(summary = "Consultar lotes por filtros de tela", description = "Consultar lotes por filtros editáveis de tela", tags={ "lote" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Consulta realizada com sucesso", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = LoteGrid.class)))),
        
        @ApiResponse(responseCode = "400", description = "Dados inválidos para consulta"),
        
        @ApiResponse(responseCode = "404", description = "Dados não encontrados para os parâmetros informados") })
    @RequestMapping(value = "/contribuintesLoteNotificacao/consultarPorFiltro",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<LoteGrid>> consultarPorFiltroContribLoteNotificacao(@Parameter(in = ParameterIn.HEADER, description = "data do período inicial" ,required=true,schema=@Schema()) @RequestHeader(value="dataInicial", required=true) String dataInicial
, @Parameter(in = ParameterIn.HEADER, description = "data do período final" ,required=true,schema=@Schema()) @RequestHeader(value="dataFinal", required=true) String dataFinal
, @Parameter(in = ParameterIn.HEADER, description = "ID do lote" ,required=true,schema=@Schema()) @RequestHeader(value="idLote", required=true) String idLote
, @Parameter(in = ParameterIn.HEADER, description = "Total de registros por página" ,required=true,schema=@Schema()) @RequestHeader(value="totalRegistrosPagina", required=true) String totalRegistrosPagina
, @Parameter(in = ParameterIn.HEADER, description = "Número da página atual" ,required=true,schema=@Schema()) @RequestHeader(value="paginaAtual", required=true) String paginaAtual
);

}

