/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.54).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import org.threeten.bp.LocalDate;
import io.swagger.model.LoteGrid;
import io.swagger.model.LoteNotificacao;
import org.threeten.bp.OffsetDateTime;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2024-04-01T14:41:59.684722023Z[GMT]")
@Validated
public interface LoteApi {

    @Operation(summary = "incluir lote", description = "Add a new lote to the contribuinte", tags={ "lote" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful operation", content = @Content(mediaType = "application/json", schema = @Schema(implementation = LoteNotificacao.class))),
        
        @ApiResponse(responseCode = "400", description = "Invalid input"),
        
        @ApiResponse(responseCode = "422", description = "Validation exception") })
    @RequestMapping(value = "/lote",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml", "application/x-www-form-urlencoded" }, 
        method = RequestMethod.POST)
    ResponseEntity<LoteNotificacao> addlote(@Parameter(in = ParameterIn.DEFAULT, description = "Create a new lote in the contribuinte", required=true, schema=@Schema()) @Valid @RequestBody LoteNotificacao body
);


    @Operation(summary = "Consultar lotes por filtros de tela", description = "Consultar lotes por filtros editáveis de tela", tags={ "lote" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Consulta realizada com sucesso", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = LoteGrid.class)))),
        
        @ApiResponse(responseCode = "400", description = "Dados inválidos para consulta"),
        
        @ApiResponse(responseCode = "404", description = "Dados não encontrados para os parâmetros informados") })
    @RequestMapping(value = "/lote/consultarPorFiltro",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<LoteGrid>> consultarPorFiltroLote(@Parameter(in = ParameterIn.HEADER, description = "data do período inicial" ,required=true,schema=@Schema()) @RequestHeader(value="dataInicial", required=true) String dataInicial
, @Parameter(in = ParameterIn.HEADER, description = "data do período final" ,required=true,schema=@Schema()) @RequestHeader(value="dataFinal", required=true) String dataFinal
, @Parameter(in = ParameterIn.HEADER, description = "ID do lote" ,required=true,schema=@Schema()) @RequestHeader(value="idLote", required=true) String idLote
, @Parameter(in = ParameterIn.HEADER, description = "Total de registros por página" ,required=true,schema=@Schema()) @RequestHeader(value="totalRegistrosPagina", required=true) String totalRegistrosPagina
, @Parameter(in = ParameterIn.HEADER, description = "Número da página atual" ,required=true,schema=@Schema()) @RequestHeader(value="paginaAtual", required=true) String paginaAtual
);


    @Operation(summary = "Consultar lotes por ID", description = "Consultar lotes por ID -  quando não utilizar lupa", tags={ "lote" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Consulta realizada com sucesso", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = LoteGrid.class)))),
        
        @ApiResponse(responseCode = "400", description = "Dados inválidos para consulta"),
        
        @ApiResponse(responseCode = "404", description = "Dados não encontrados para os parâmetros informados") })
    @RequestMapping(value = "/lote/{idLote}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<LoteGrid>> consultarPorId(@Parameter(in = ParameterIn.PATH, description = "ID do lote", required=true, schema=@Schema()) @PathVariable("idLote") String idLote
);


    @Operation(summary = "Finds lotes by status", description = "Multiple status values can be provided with comma separated strings", tags={ "lote" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = LoteNotificacao.class)))),
        
        @ApiResponse(responseCode = "400", description = "Invalid status value") })
    @RequestMapping(value = "/lote/consultar",
        produces = { "application/json", "application/xml" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<LoteNotificacao>> findlotesByStatus(@Parameter(in = ParameterIn.QUERY, description = "Status values that need to be considered for filter" ,schema=@Schema(allowableValues={ "available", "pending", "sold" }
, defaultValue="available")) @Valid @RequestParam(value = "status", required = false, defaultValue="available") String status
);


    @Operation(summary = "alterar lote", description = "Update an existing lote by Id", tags={ "lote" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful operation", content = @Content(mediaType = "application/json", schema = @Schema(implementation = LoteNotificacao.class))),
        
        @ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
        
        @ApiResponse(responseCode = "404", description = "lote not found"),
        
        @ApiResponse(responseCode = "422", description = "Validation exception") })
    @RequestMapping(value = "/lote",
        produces = { "application/json", "application/xml" }, 
        consumes = { "application/json", "application/xml", "application/x-www-form-urlencoded" }, 
        method = RequestMethod.PUT)
    ResponseEntity<LoteNotificacao> updatelote(@Parameter(in = ParameterIn.DEFAULT, description = "Update an existent lote in the contribuinte", required=true, schema=@Schema()) @Valid @RequestBody LoteNotificacao body
);

}

